apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: alloydb-flights
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: gcp-native
connection:
  type: database
  provider: gcp-alloydb
  resource: flights_dataset
  capabilities:
    supportsMcpToolbox: true
    mcpToolset: postgres-database-tools
auth:
  method: password
  secretRefs:
    - alloydb-postgres-user
    - alloydb-postgres-password
secrets:
  provider: gcpSecretManager
  inheritFromWdf: true
  secretRefs:
    - name: alloydb-postgres-user
      injectAs: env
      envVar: ALLOYDB_POSTGRES_USER
      externalRef:
        provider: gcp-secret-manager
        vaultRef: gcp-main
        key: alloydb-postgres-user
    - name: alloydb-postgres-password
      injectAs: env
      envVar: ALLOYDB_POSTGRES_PASSWORD
      externalRef:
        provider: gcp-secret-manager
        vaultRef: gcp-main
        key: alloydb-postgres-password
    - name: mcp-toolbox-host
      injectAs: env
      envVar: MCP_TOOLBOX_HOST
      externalRef:
        provider: gcp-secret-manager
        vaultRef: gcp-main
        key: mcp-toolbox-host
    - name: mcp-toolbox-port
      injectAs: env
      envVar: MCP_TOOLBOX_PORT
      source_type: literal_non_secret
      value: "8080"
